title: Test site 
author: mssil3
email: shawn.marconi@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Just trying to learn as much as I can

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
